// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu_WebApp.Models.EF;

#nullable disable

namespace QuanLyChiTieu_WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111060720_AddNotificationTable")]
    partial class AddNotificationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetID"));

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BudgetID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IconID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("ColorID");

                    b.HasIndex("IconID");

                    b.HasIndex("UserID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorID"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorID");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorID = 1,
                            ColorName = "Red",
                            HexCode = "#ef4444"
                        },
                        new
                        {
                            ColorID = 2,
                            ColorName = "Orange",
                            HexCode = "#f97316"
                        },
                        new
                        {
                            ColorID = 3,
                            ColorName = "Amber",
                            HexCode = "#f59e0b"
                        },
                        new
                        {
                            ColorID = 4,
                            ColorName = "Yellow",
                            HexCode = "#eab308"
                        },
                        new
                        {
                            ColorID = 5,
                            ColorName = "Lime",
                            HexCode = "#84cc16"
                        },
                        new
                        {
                            ColorID = 6,
                            ColorName = "Green",
                            HexCode = "#22c55e"
                        },
                        new
                        {
                            ColorID = 7,
                            ColorName = "Emerald",
                            HexCode = "#10b981"
                        },
                        new
                        {
                            ColorID = 8,
                            ColorName = "Teal",
                            HexCode = "#14b8a6"
                        },
                        new
                        {
                            ColorID = 9,
                            ColorName = "Cyan",
                            HexCode = "#06b6d4"
                        },
                        new
                        {
                            ColorID = 10,
                            ColorName = "Sky",
                            HexCode = "#0ea5e9"
                        },
                        new
                        {
                            ColorID = 11,
                            ColorName = "Blue",
                            HexCode = "#3b82f6"
                        },
                        new
                        {
                            ColorID = 12,
                            ColorName = "Indigo",
                            HexCode = "#6366f1"
                        },
                        new
                        {
                            ColorID = 13,
                            ColorName = "Violet",
                            HexCode = "#8b5cf6"
                        },
                        new
                        {
                            ColorID = 14,
                            ColorName = "Purple",
                            HexCode = "#a855f7"
                        },
                        new
                        {
                            ColorID = 15,
                            ColorName = "Fuchsia",
                            HexCode = "#d946ef"
                        },
                        new
                        {
                            ColorID = 16,
                            ColorName = "Pink",
                            HexCode = "#ec4899"
                        },
                        new
                        {
                            ColorID = 17,
                            ColorName = "Rose",
                            HexCode = "#f43f5e"
                        },
                        new
                        {
                            ColorID = 18,
                            ColorName = "Slate",
                            HexCode = "#64748b"
                        },
                        new
                        {
                            ColorID = 19,
                            ColorName = "Gray",
                            HexCode = "#9ca3af"
                        },
                        new
                        {
                            ColorID = 20,
                            ColorName = "Stone",
                            HexCode = "#a8a29e"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Goal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalID"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang thực hiện");

                    b.Property<decimal>("TargetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WalletID")
                        .HasColumnType("int");

                    b.HasKey("GoalID");

                    b.HasIndex("UserID");

                    b.HasIndex("WalletID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.GoalDeposit", b =>
                {
                    b.Property<int>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DepositDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GoalID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WalletID")
                        .HasColumnType("int");

                    b.HasKey("DepositID");

                    b.HasIndex("GoalID");

                    b.HasIndex("UserID");

                    b.HasIndex("WalletID");

                    b.ToTable("GoalDeposits", t =>
                        {
                            t.HasCheckConstraint("CK_GoalDeposit_Amount_Positive", "Amount > 0");
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Icon", b =>
                {
                    b.Property<int>("IconID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IconID"));

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IconID");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            IconID = 1,
                            IconClass = "fa-solid fa-utensils",
                            IconName = "Ăn uống"
                        },
                        new
                        {
                            IconID = 2,
                            IconClass = "fa-solid fa-bus-simple",
                            IconName = "Đi lại"
                        },
                        new
                        {
                            IconID = 3,
                            IconClass = "fa-solid fa-gas-pump",
                            IconName = "Xăng xe"
                        },
                        new
                        {
                            IconID = 4,
                            IconClass = "fa-solid fa-file-invoice-dollar",
                            IconName = "Hóa đơn"
                        },
                        new
                        {
                            IconID = 5,
                            IconClass = "fa-solid fa-house-user",
                            IconName = "Thuê nhà"
                        },
                        new
                        {
                            IconID = 6,
                            IconClass = "fa-solid fa-shirt",
                            IconName = "Mua sắm"
                        },
                        new
                        {
                            IconID = 7,
                            IconClass = "fa-solid fa-cart-shopping",
                            IconName = "Tạp hóa"
                        },
                        new
                        {
                            IconID = 8,
                            IconClass = "fa-solid fa-screwdriver-wrench",
                            IconName = "Sửa chữa"
                        },
                        new
                        {
                            IconID = 9,
                            IconClass = "fa-solid fa-heart-pulse",
                            IconName = "Sức khỏe"
                        },
                        new
                        {
                            IconID = 10,
                            IconClass = "fa-solid fa-graduation-cap",
                            IconName = "Giáo dục"
                        },
                        new
                        {
                            IconID = 11,
                            IconClass = "fa-solid fa-film",
                            IconName = "Giải trí"
                        },
                        new
                        {
                            IconID = 12,
                            IconClass = "fa-solid fa-dumbbell",
                            IconName = "Thể thao"
                        },
                        new
                        {
                            IconID = 13,
                            IconClass = "fa-solid fa-wand-magic-sparkles",
                            IconName = "Làm đẹp"
                        },
                        new
                        {
                            IconID = 14,
                            IconClass = "fa-solid fa-mug-hot",
                            IconName = "Cà phê"
                        },
                        new
                        {
                            IconID = 15,
                            IconClass = "fa-solid fa-plane-departure",
                            IconName = "Du lịch"
                        },
                        new
                        {
                            IconID = 16,
                            IconClass = "fa-solid fa-palette",
                            IconName = "Sở thích"
                        },
                        new
                        {
                            IconID = 17,
                            IconClass = "fa-solid fa-gift",
                            IconName = "Quà tặng"
                        },
                        new
                        {
                            IconID = 18,
                            IconClass = "fa-solid fa-child-reaching",
                            IconName = "Con cái"
                        },
                        new
                        {
                            IconID = 19,
                            IconClass = "fa-solid fa-paw",
                            IconName = "Thú cưng"
                        },
                        new
                        {
                            IconID = 20,
                            IconClass = "fa-solid fa-money-bill-wave",
                            IconName = "Lương"
                        },
                        new
                        {
                            IconID = 21,
                            IconClass = "fa-solid fa-briefcase",
                            IconName = "Kinh doanh"
                        },
                        new
                        {
                            IconID = 22,
                            IconClass = "fa-solid fa-arrow-trend-up",
                            IconName = "Đầu tư"
                        },
                        new
                        {
                            IconID = 23,
                            IconClass = "fa-solid fa-piggy-bank",
                            IconName = "Tiết kiệm"
                        },
                        new
                        {
                            IconID = 24,
                            IconClass = "fa-solid fa-sack-dollar",
                            IconName = "Thu nhập phụ"
                        },
                        new
                        {
                            IconID = 25,
                            IconClass = "fa-solid fa-shield-halved",
                            IconName = "Bảo hiểm"
                        },
                        new
                        {
                            IconID = 26,
                            IconClass = "fa-solid fa-building-columns",
                            IconName = "Ngân hàng"
                        },
                        new
                        {
                            IconID = 27,
                            IconClass = "fa-solid fa-store",
                            IconName = "Cửa hàng"
                        },
                        new
                        {
                            IconID = 28,
                            IconClass = "fa-solid fa-mobile-screen-button",
                            IconName = "Điện thoại"
                        },
                        new
                        {
                            IconID = 29,
                            IconClass = "fa-solid fa-wifi",
                            IconName = "Internet"
                        },
                        new
                        {
                            IconID = 30,
                            IconClass = "fa-solid fa-ellipsis",
                            IconName = "Khác"
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketID");

                    b.HasIndex("UserID");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_Status", "Status IN ('Open','Pending','Resolved')");
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WalletID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.HasIndex("WalletID");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Amount_Positive", "Amount > 0");

                            t.HasCheckConstraint("CK_Transaction_Type", "Type IN (N'Expense', N'Income')");
                        });
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletID"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("InitialBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WalletID");

                    b.HasIndex("UserID");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Budget", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Category", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Icon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Goal", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Wallet", null)
                        .WithMany("Goals")
                        .HasForeignKey("WalletID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.GoalDeposit", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Goal", "Goal")
                        .WithMany("GoalDeposits")
                        .HasForeignKey("GoalID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("GoalDeposits")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Wallet", "Wallet")
                        .WithMany("GoalDeposits")
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Notification", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Ticket", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Transaction", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Wallet", b =>
                {
                    b.HasOne("QuanLyChiTieu_WebApp.Models.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Goal", b =>
                {
                    b.Navigation("GoalDeposits");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.User", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("GoalDeposits");

                    b.Navigation("Goals");

                    b.Navigation("Notifications");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("QuanLyChiTieu_WebApp.Models.Entities.Wallet", b =>
                {
                    b.Navigation("GoalDeposits");

                    b.Navigation("Goals");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
